services:

  backend:
    image: big-nest-forum/backend
    build: ./backend
    links:
      - db
    ports:
      - "8080:8080"

  frontend:
    image: big-nest-forum/frontend
    build: ./frontend
    ports:
      - "3300:3300"

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 's3cret'
    volumes:
      - './db/pgdata/:/var/lib/postgresql/data/'

