services:

  backend:
    image: big-nest-forum/backend
    build: ./backend
    links:
      - db
    ports:
      - "8080:8080"
    stdin_open: true
    tty: true
    env_file: .env


  frontend:
    image: big-nest-forum/frontend
    build: 
      context: ./frontend
      args:
        - FRONTEND_PORT=${FRONTEND_PORT}
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    env_file: .env

  db:
    image: big-nest-forum/db
    build: ./db
    ports:
      - "5432:5432"
    volumes:
      - './db/pgdata/:/var/lib/postgresql/data/'
    environment:
      POSTGRES_DB: big_nest_forum
    env_file: .env

