#FROM gradle:6.9.4-jdk17-alpine AS build
FROM eclipse-temurin:17-alpine AS build
WORKDIR /build
#COPY ./.env .
COPY . .
RUN ./gradlew build

FROM eclipse-temurin:17-alpine
WORKDIR /app
COPY --from=build /build/build/libs/bignestforum-0.0.1-SNAPSHOT.jar ./app.jar
#COPY --from=build /build/.env ./.env
CMD ["java", "-jar", "./app.jar"]
