CREATE TABLE forum_category (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR NOT NULL UNIQUE
);

CREATE TABLE forum (
    id VARCHAR PRIMARY KEY,
    category_id INT NOT NULL REFERENCES forum_category(id) ON DELETE NO ACTION,
    name VARCHAR NOT NULL UNIQUE
);

CREATE TABLE account (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    blocked BOOLEAN NOT NULL DEFAULT FALSE,
    username VARCHAR NOT NULL UNIQUE,
    password_hash VARCHAR NOT NULL,
    role ENUM ('USER', 'OWNER', 'ADMIN', 'MODER') NOT NULL DEFAULT 'USER'
);